### ISSUE TITLE
Sample app behaves like a virus with likely harmful results!

### ISSUE THREAD

**Issue by art-ist** [microsoftgraph/console-csharp-snippets-sample#1]
Nearly under every circumstance **it is harmful to run this sample code!**

Actually sending an email:
- impersonating the user, 
- to random recipients in his or her company and beyond 
- and this without any specific consent (or a very explicit warning in the README at least) 

is **aggressive and unacceptable for a sample app**!

_(See: file UserMode.cs, Line 215 and below.)_

**Without prior prompt or warning** this sample sends an email to a disclosed list of recipients with the logged in user as the sender. 
- This is damaging to the user's reputation. 
- Furthermore possibly confidential and private information is disclosed, leaking possibly confidential information of the company using the Microsoft Graph.
- The confirmation message then misleads the user, reporting: `"\nMail sent to {0}", currentUser.DisplayName` without mentioning the **other 10 recipients**.

The current behavior is a **severe misuse of the trust in code published by Microsoft or the Microsoft Graph**.

Why not just sending that sample email to the logged in user alone?

@jamescro: I urgently request a review of the sample, and a fix of all security issues to the idea of "Secure by default"!

**Comment by MIchaelMainer** [comment]
@art-ist You are totally correct! This is not acceptable. I'm sorry if this has caused any issues for you. I ran this as an ad hoc test for an update to the client library and just saw this behavior.

I will fix this.
