### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by kp2017-zz** [microsoftgraph/console-csharp-snippets-sample#7]
I believe the [documentation ](https://docs.microsoft.com/en-us/samples/microsoftgraph/console-csharp-snippets-sample/microsoft-graph-c-console-snippets-app/)may be out of date 

> Select the Add a Redirect URI link. On the Redirect URIs page, locate the Suggested Redirect URIs for public clients (mobile, desktop) section. Select the URI that begins with msal and the urn:ietf:wg:oauth:2.0:oob URI.

Currently AAD doesn't have this suggestion redirect. Have they changed AAD since this was written?

**Comment by jasonjoh** [comment]
Closing this as we are archiving this sample and no longer maintaining it. As a replacement, please see the https://github.com/microsoftgraph/msgraph-training-dotnet-core repository.
